config/routes.rb
Vacationr::Application.routes.draw do
  resources :vacations

end

app/models/vacation.rb
class Vacation < ActiveRecord::Base
  attr_accessible :lat, :long, :name, :zoom
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/vacations_controller.rb
class VacationsController < ApplicationController
  # GET /vacations
  # GET /vacations.json
  def index
    @vacations = Vacation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @vacations }
    end
  end

  # GET /vacations/1
  # GET /vacations/1.json
  def show
    @vacation = Vacation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @vacation }
    end
  end

  # GET /vacations/new
  # GET /vacations/new.json
  def new
    @vacation = Vacation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @vacation }
    end
  end

  # GET /vacations/1/edit
  def edit
    @vacation = Vacation.find(params[:id])
  end

  # POST /vacations
  # POST /vacations.json
  def create

  place = Geocoder.search(params[:vacation][:name])
  lat = place[0].latitude
  long = place[0].longitude
  addr = place[0].address

  @vacation = Vacation.new
  @vacation.name = addr
  @vacation.lat = lat
  @vacation.long = long
  @vacation.zoom = params[:vacation][:zoom]




    respond_to do |format|
      if @vacation.save
        format.html { redirect_to @vacation, notice: 'Vacation was successfully created.' }
        format.json { render json: @vacation, status: :created, location: @vacation }
      else
        format.html { render action: "new" }
        format.json { render json: @vacation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /vacations/1
  # PUT /vacations/1.json
  def update
    @vacation = Vacation.find(params[:id])

    respond_to do |format|
      if @vacation.update_attributes(params[:vacation])
        format.html { redirect_to @vacation, notice: 'Vacation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @vacation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vacations/1
  # DELETE /vacations/1.json
  def destroy
    @vacation = Vacation.find(params[:id])
    @vacation.destroy

    respond_to do |format|
      format.html { redirect_to vacations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vacations_helper.rb
module VacationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vacationr</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{GOOGLEKEY}&sensor=false" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/vacations/_form.html.erb
<%= form_for(@vacation) do |f| %>
  <% if @vacation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vacation.errors.count, "error") %> prohibited this vacation from being saved:</h2>

      <ul>
      <% @vacation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lat %><br />
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :long %><br />
    <%= f.text_field :long %>
  </div>
  <div class="field">
    <%= f.label :zoom %><br />
    <%= f.number_field :zoom %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vacations/_map.html.erb
<div id="map_canvas"></div>

<script>
  display_map(<%= lat %>, <%= long %>, <%= zoom %>)
</script>

app/views/vacations/_pin.html.erb
<script>
  add_marker(<%= vacation.lat %>, <%= vacation.long %>, '<%= vacation.name %>')
</script>

app/views/vacations/edit.html.erb
<h1>Editing vacation</h1>

<%= render 'form' %>

<%= link_to 'Show', @vacation %> |
<%= link_to 'Back', vacations_path %>

app/views/vacations/index.html.erb
<h1>Listing vacations</h1>


<%= render :partial => 'map', :locals => {:lat => 0, :long => 0, :zoom => 2} %>

<%= render :partial => 'pin', :collection => @vacations, :as => :vacation %>

<table>
  <tr>
    <th>Name</th>
    <th>Lat</th>
    <th>Long</th>
    <th>Zoom</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @vacations.each do |vacation| %>
  <tr>
    <td><%= vacation.name %></td>
    <td><%= vacation.lat %></td>
    <td><%= vacation.long %></td>
    <td><%= vacation.zoom %></td>
    <td><%= link_to 'Show', vacation %></td>
    <td><%= link_to 'Edit', edit_vacation_path(vacation) %></td>
    <td><%= link_to 'Destroy', vacation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Vacation', new_vacation_path %>

app/views/vacations/new.html.erb
<h1>New vacation</h1>

<%= render 'form' %>

<%= link_to 'Back', vacations_path %>

app/views/vacations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @vacation.name %>
</p>

<%= render :partial => 'map', :locals => {:lat => @vacation.lat, :long => @vacation.long, :zoom => @vacation.zoom} %>

<%= render :partial => 'pin', :locals => {:vacation => @vacation} %>


<%= link_to 'Edit', edit_vacation_path(@vacation) %> |
<%= link_to 'Back', vacations_path %>